services:
  highscore-mysql:
    hostname: mysql
    image: mysql:lts
    environment:
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
      - mysql_data:/var/lib/mysql
    networks:
      highscore_net:
  highscore-service:
    hostname: highscore-service
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile
    environment:
      - HIGHSCORE_SERVICE_DB_USER=devuser
      - HIGHSCORE_SERVICE_DB_PASS=devpassword
      - HIGHSCORE_SERVICE_DB_ADDRESS=mysql:3306
      - HIGHSCORE_SERVICE_DB_NAME=DBScores
      - HIGHSCORE_SERVICE_DB_SCORETABLE_NAME=Scores
      - HIGHSCORE_SERVICE_DB_GAMETABLE_NAME=Games
      - HIGHSCORE_SERVICE_HOST=highscore-service
      - HIGHSCORE_SERVICE_PORT=80
    ports:
      - "9999:80"
    volumes:
      - ./config/config.json:/etc/highscore/config.json:ro
    networks:
      highscore_net:
    depends_on:
      - highscore-mysql
  
volumes:
  mysql_data:

networks:
  highscore_net: